version: "3.8"

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            -   ./:/var/www/html
            -   ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            -   ./logs/nginx:/var/log/nginx
        ports:
            -   "8000:8000"
            -   "3000:443"
        restart: always
        depends_on:
            -   laravel
            -   mysql
        networks:
            - backend

    laravel:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: laravel
        volumes:
            - ./:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        depends_on:
            - mysql
            - redis
        networks:
            - backend

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - "6380:6379"
        volumes:
            - ./redis-data:/data
        networks:
            - backend

    mysql:
        image: mysql:8.4
        container_name: ${MYSQL_HOST}
        ports:
            - "8990:3306"
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        restart: always
        volumes:
            - ./local_db:/var/lib/mysql
        networks:
            - backend


networks:
    backend:
        driver: bridge
